import type { Metadata } from "next";
import localFont from 'next/font/local'
import "./globals.css";

const inter = localFont({
  src: './fonts/interVF.ttf', // Adjust the path based on your project structure
  variable: '--font-inter', // Custom CSS variable
  display: 'swap',
  weight: '100 200 300 400 500 600 700 800 900',
})

const spaceGrotesk = localFont({
  src: './fonts/SpaceGroteskVF.ttf', // Adjust the path based on your project structure
  variable: '--font-space-grotesk', // Custom CSS variable
  display: 'swap',
  weight: '300 400 500 600 700 800 900',
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({children}: Readonly<{children: React.ReactNode}>) {
  return (
    <html lang="en">
      <body className={`${inter.variable} ${spaceGrotesk.variable} antialiased`}>
        {children}
      </body>
    </html>
  )
}
